language: ruby
cache: bundler
rvm: 2.4.0
gemfile: src/api/Gemfile
before_install: dist/ci/travis_before_install.sh
before_script: dist/ci/travis_before_script.sh
after_failure: dist/ci/travis_after_failure.sh
script:
  - "dist/ci/travis_script.sh $TEST_SUITE"
dist: trusty
sudo: required
env:
  - TEST_SUITE=rspec
  - TEST_SUITE=api
  - TEST_SUITE=webui
  - TEST_SUITE=spider
  - TEST_SUITE=backend
matrix:
  fast_finish: true
  include:
  - rvm:
    env: TEST_SUITE=jshint
    before_install: npm install -g jshint
    install: ''
    before_script: ''
  - env: TEST_SUITE=rubocop
    cache:
      bundler: true
      directories:
        - tmp/rubocop_cache
    before_install: ''
    before_script: ''
services:
  - memcached
