language: ruby
cache: bundler
rvm: 2.3.0
gemfile: src/api/Gemfile
before_install: dist/ci/obs_testsuite_travis_install.sh
before_script: dist/ci/obs_testsuite_travis_before.sh
after_failure: dist/ci/obs_testsuite_travis_failure.sh
script: "dist/ci/obs_testsuite_travis.sh $TEST_SUITE"
env:
  - TEST_SUITE=jshint
  - TEST_SUITE=rubocop
  - TEST_SUITE=rspec
  - TEST_SUITE=api
  - TEST_SUITE=webui
  - TEST_SUITE=spider
matrix:
  fast_finish: true
notifications:
  irc:
     channels:
       - "chat.freenode.net#opensuse-buildservice"
     on_success: change
     on_failure: change
services:
  - memcached
sudo: required
