# Machine config
dist: trusty
sudo: required
services:
  - docker

# Language and app config
language: ruby

#cache:
#  directories:
#    - src/api/vendor/bundle
# Github config
branches:
  except:
    # starting with depfu/
    - /^depfu\/.*/

# Scripts
after_failure: dist/ci/travis_after_failure.sh
 # we need to chown the build dir to frontend:users (1000:100) to avoid permission errors
before_script: sudo chown 1000:100 $TRAVIS_BUILD_DIR -R
script: "dist/ci/travis_script.sh $TEST_SUITE"

# Notifications
notifications:
  irc:
     channels:
       - "chat.freenode.net#opensuse-buildservice"
     on_success: change
     on_failure: change

# Jobs matrix and stages 
jobs:
  include:
    - stage: Linters
      env: TEST_SUITE=linter
      cache:
        directories:
          - src/api/tmp/rubocop_cache
    - stage: test
      env: TEST_SUITE=rspec
    - env: TEST_SUITE=api
    - env: TEST_SUITE=spider
    - env: TEST_SUITE=backend
  fast_finish: true
