language: ruby
rvm:
  - 2.0.0
before_script: 
  - mysql -e 'create database ci_api_test;'
  - sed -e 's,password:.*,password:,' -i src/api/config/database.yml.example
  - travis_retry bash -x dist/ci/obs_testsuite_travis_before.sh
  - bash -x dist/ci/obs_testsuite_travis_setup.sh
script: bash -x dist/ci/obs_testsuite_travis.sh
env:
  # just one special test
  #- SUBTEST=api:functional/public_controller_test.rb:test_binaries
  #- SUBTEST=rake:test:api
  #- SUBTEST=rake:test:webui
  # api and webui webrat with latest gems
  #- SUBTEST=rake:test REMOVEGEMLOCK=true
matrix:
  allow_failures:
    - env: SUBTEST=rake:test REMOVEGEMLOCK=true
notifications:
  email:
    on_success: change
    on_failure: change

