version: "2.1"
services:
  db:
    image: openbuildservice/mariadb
    ports:
      - "3306:3306"
  cache:
    image: openbuildservice/memcached
    ports:
      - "11211:11211"
  backend:
    image: openbuildservice/backend
    volumes:
      - .:/obs
      - ./dist/aws_credentials:/etc/obs/cloudupload/.aws/config
      - ./dist/ec2utils.conf:/etc/obs/cloudupload/.ec2utils.conf
      - ./dist/clouduploader.rb:/usr/bin/clouduploader
    command: /obs/contrib/start_development_backend -d /obs
  worker:
    image: openbuildservice/backend
    volumes:
      - .:/obs
    privileged: true
    depends_on:
      - backend
    command: /obs/contrib/start_development_worker
  frontend:
    image: openbuildservice/frontend
    command: foreman start -p 3000
    build:
      dockerfile: docker-files/Dockerfile
      context: src/api
    volumes:
      - .:/obs
    ports:
      - "3000:3000"
      - "1080:1080"
    environment:
      RSPEC_HOST: frontend
    depends_on:
      - db
      - cache
      - backend
      - worker
      - selenium
  selenium:
    image: selenium/standalone-chrome-debug
    environment:
      VNC_NO_PASSWORD: 1
    ports:
      - 5900:5900

