version: 2.0

images:
  - &common_frontend_config
    user: frontend
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: 1

  - &mariadb
    image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/containers/openbuildservice/mariadb:latest
    command: |
      /bin/bash -c 'echo -e "[mysqld]\ndatadir = /dev/shm" > /etc/my.cnf.d/obs.cnf && cp -a /var/lib/mysql/* /dev/shm && /usr/lib/mysql/mysql-systemd-helper start'
    name: db

  - &backend registry.opensuse.org/obs/server/unstable/container/sle12/sp3/containers/openbuildservice/backend:latest

  - &frontend_backend
    image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/containers/openbuildservice/frontend-backend:latest
    <<: *common_frontend_config
    environment:
      EAGER_LOAD: 1

  - &frontend_base
    image: registry.opensuse.org/obs/server/unstable/container/sle12/sp3/containers/openbuildservice/frontend-base:latest
    <<: *common_frontend_config

aliases:
  - &install_dependencies
    name: install dependencies
    command: |
      cd ./src/api && bundle install --jobs=4 --retry=3

  - &wait_for_database
    name: Wait for DB
    command: mysqladmin ping -h db

  - &init_git_submodule
    name: Init submodule
    command: git submodule update --init --recursive --remote

  - &create_test_db
    name: Create database
    command: cd src/api; bundle exec rake db:create db:setup RAILS_ENV=test

  - &bootstrap_old_test_suite
    name: Setup application
    command: cd src/api; bundle exec rake dev:bootstrap[old_test_suite] RAILS_ENV=test

  - &start_remote_backend
    name: Start Backend
    command: |
      sed -e "s,@CIRCLE_REPOSITORY_URL@,$CIRCLE_REPOSITORY_URL,; s,@CIRCLE_SHA1@,$CIRCLE_SHA1," -i contrib/trigger_checkout
      nc backend 4000 < contrib/trigger_checkout

  # keep the prefix for the following aligned
  - &save_repo_cache_key
    key: v3-repo-{{ .Branch }}-{{ .Revision }}

  - &initial_repo_restore
    restore_cache:
      keys:
        - v3-repo-{{ .Branch }}-{{ .Revision }}
        - v3-repo-{{ .Branch }}
        - v3-repo

  - &restore_repo
    restore_cache:
      keys:
        - v3-repo-{{ .Branch }}-{{ .Revision }}

  - &store_minitest_artefacts
    store_artifacts:
      path: ./src/api/log/
      destination: minitest

  - &install_circle_cli
    name: Install CircleCI command line
    command: |
      curl -o circleci https://circle-downloads.s3.amazonaws.com/releases/build_agent_wrapper/circleci
      chmod +x circleci

jobs:
  checkout_code:
    docker:
      - <<: *frontend_base
    steps:
      - *initial_repo_restore
      - checkout
      - run: *install_dependencies
      - run: *install_circle_cli
      - restore_cache:
          key: v4-lint
      - run:
          name: Install jshint
          command: sudo npm install -g jshint
      - run:
          name: Run linters
          command: cd src/api; bundle exec rake dev:lint RAILS_ENV=test
      - save_cache:
          key: v4-lint-{{ epoch }}
          paths:
            - src/api/tmp/rubocop_cache_root_dir
            - src/api/tmp/rubocop_cache_rails_dir
      - run: rm -rf src/api/tmp/rubocop*
      - run:
          name: Setup application
          command: cd src/api; bundle exec rake dev:prepare assets:precompile RAILS_ENV=test
      - save_cache:
          <<: *save_repo_cache_key
          paths:
            - .

  rspec:
    parallelism: 4
    docker:
      - <<: *frontend_base
      - <<: *mariadb
      - image: *backend
        name: backend
        user: frontend
        command: /bin/bash /remote_executor.sh
    steps:
      - *restore_repo
      - run: *install_dependencies
      - run: *start_remote_backend
      - run: *wait_for_database
      - run: *create_test_db
      - run: mkdir /home/frontend/rspec
      - run:
          name: Run rspec
          command: |
            cd src/api
            pickfile=log/pick.$CIRCLE_NODE_INDEX.list
            # reserve the latest node for bootstrap
            if test "$CIRCLE_NODE_INDEX" = $((CIRCLE_NODE_TOTAL-1)); then
              echo "Testing bootstrap"
              circleci tests glob 'spec/features/**/*_spec.rb' 'spec/bootstrap/**/*_spec.rb' > $pickfile
              export BOOTSTRAP=1
            else
              circleci tests glob 'spec/**/*_spec.rb' | grep -v spec/bootstrap > spec.list
              circleci tests split --total $((CIRCLE_NODE_TOTAL-1)) --split-by=timings < spec.list > $pickfile
            fi
            bundle exec rspec --format progress --format RspecJunitFormatter -o /home/frontend/rspec/rspec.xml $(cat $pickfile)
      - store_artifacts:
          path: ./src/api/log
          destination: rspec
      - store_artifacts:
          path: ./src/api/tmp/capybara
          destination: capybara
      - store_test_results:
          path: /home/frontend/rspec

  minitest:
    parallelism: 2
    docker:
      - <<: *frontend_backend
      - <<: *mariadb
    steps:
      - *restore_repo
      - run: *install_dependencies
      - run: *init_git_submodule
      - run: *wait_for_database
      - run:
          name: Check DB Structure
          command: |
            cd src/api;
            bundle exec rake dev:lint:db RAILS_ENV=test
      - run: *bootstrap_old_test_suite
      - run: mkdir /home/frontend/minitest
      - run:
          name: Run minitest
          environment:
            DO_COVERAGE: 1
            TESTOPTS: "--ci-dir=/home/frontend/minitest"
          command: |
            cd src/api
            case $CIRCLE_NODE_INDEX in
              0)
                bundle exec rake test:api:models
                ;;
              1)
                bundle exec rake test:api:functional
                ;;
            esac
      - store_test_results:
          path: /home/frontend/minitest
      - <<: *store_minitest_artefacts

  spider:
    docker:
      - <<: *frontend_backend
      - <<: *mariadb
    steps:
      - *restore_repo
      - run: *install_dependencies
      - run: *init_git_submodule
      - run: *wait_for_database
      - run: *bootstrap_old_test_suite
      - run:
          name: Run spider
          command: cd src/api; bundle exec rake test:spider
      - <<: *store_minitest_artefacts

  backend_test:
    docker:
      - image: *backend
    working_directory: /home/frontend/project
    steps:
      - *restore_repo
      - run: *init_git_submodule
      - run:
          name: backend
          command: make -C src/backend test

workflows:
  version: 2
  test_all:
    jobs:
      - checkout_code
      - backend_test:
          requires:
            - checkout_code
      - rspec:
          requires:
            - checkout_code
      - minitest:
          requires:
            - checkout_code
      - spider:
          requires:
            - checkout_code
