# Config options for the buildservice webclient
version: 1.0

# change this option to use a customized theme. See README.theme
theme: neutral
# this is build.opensuse.org's theme
#theme: bento

# Set this when the webclient runs from a subdirectory
#relative_url_root: /stage

# Set this when the api runs from a subdirectory
#api_relative_url_root: /stage

# Exceptions get mailed to these addresses:
#exception_recipients: ['webclient_noreply@opensuse.org']
exception_recipients: []

# Define a name for this OBS instance name, will be visible where ever 
# "Open Build Service" term is used in the webui
#visible_instance_name: "Private"

# Use static.opensuse.org for static style content
#use_static: build.o.o

# Download base URL of published binaries
#download_url: http://myhost:82/

# Bugzilla link url for creating bugreports for projects or packages
#bugzilla_host: http://bugzilla.myproject.org

# Hide private options in webui, like source or binary protection 
# hide_private_options: true

# Make use of mod_xforward module in apache
#use_xforward: true

# make use of http://blog.lighttpd.net/articles/2006/07/22/x-sendfiles-new-friend-x-rewrite
# note that you need to enable the proxy-core option to allow this
#use_lighttpd_x_rewrite: true
