#exception_recipients: ['webclient_noreply@opensuse.org']

# add also webui_host setting if you want allow anonymous read access via webui
#allow_anonymous: true
#webui_host: build.opensuse.org

# should be set always
webui_url: http://localhost:3000

# make use of http://blog.lighttpd.net/articles/2006/07/22/x-sendfiles-new-friend-x-rewrite
# note that you need to enable the proxy-core option to allow this
#x_rewrite_host: localhost

