name: Brakeman

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container: ruby:3.1.4
    steps:
    - uses: actions/checkout@v3
    - name: Install Brakeman
      run: |
        gem install --no-format-executable brakeman -v 5.4.0
    - name: Brakeman
      run: |
        brakeman -p src/api
